name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  lint:
  
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: super-linter/super-linter@v5.0.0

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
